server:
  port: 9090

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
#    org.springframework.boot.autoconfigure: DEBUG

spring:
  thymeleaf:
    cache: false
    
  security:
    oauth2:
      client:
        registration:
            google:
                  clientId: 323063629110-gm4ji93vuncugb18jhklt0k96brordtv.apps.googleusercontent.com
                  clientSecret: ERnCn8eP6YL_V9Rb5l-lcod_
                  #redirectUriTemplate: "{baseUrl}/login/oauth2/code/{registrationId}"
                  
                  #redirectUriTemplate: "{baseUrl}/oauth2/callback/{registrationId}"
                  #client-authentication-method: basic
                  #redirectUriTemplate: "{baseUrl}/oauth2/callback/{registrationId}"
                  #scope: openid, profile, email, address, phone
                  #client-name: Google
#        provider:
#            google:
#                     authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
#                     token-uri: https://www.googleapis.com/oauth2/v4/token
#                     user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
#                     user-name-attribute: sub
#                     jwk-set-uri: https://www.googleapis.com/oauth2/v2/certs 
#          
    
        
              